# Generated by Django 3.2.4 on 2022-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_img'),
        ),
    ]
